services:
  shortener:
    container_name: url-shortener
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=${NODE_ENV}
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - DATABASE_PATH=${DATABASE_PATH}
      - PORT=${PORT}
    ports:
      - "${PORT}:3000"
    mem_limit: 512m
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.url-shortener.rule=Host(`s.lan.thenaha.my.id`)
      - traefik.http.services.url-shortener.loadbalancer.server.port=3000
    networks:
      - proxy

networks:
  proxy:
    external: true

